### ISSUE TITLE
data - redfish_dell_idrac_attributes - "unexpected end of JSON input"

### ISSUE THREAD

**Issue by robbycuenot** [dell/terraform-provider-redfish#164] opened 2024-01-26 15:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Redfish Provider Version

Terraform Cloud Workspace Version 1.7.0
Redfish Provider Version 1.1.0

### Server(s) details and firmware version

Dell R930 (D8KQRD2)

iDRAC 8
BIOS Version 2.13.0
Firmware Version 2.85.85.85

### Affected Resource(s)

data "redfish_dell_idrac_attributes"

### Terraform Configuration Files 

```hcl
terraform {
  required_providers {
    redfish = {
      source = "dell/redfish"
      version = "1.1.0"
    }
  }
}

provider "redfish" {
    user = var.idrac_username
    password = var.idrac_password
}

data "redfish_dell_idrac_attributes" "idrac" {
  redfish_server {
    endpoint      = var.r930_idrac_endpoint
    ssl_insecure = true
  }
}

data "redfish_bios" "bios" {
  redfish_server {
    endpoint      = var.r930_idrac_endpoint
    ssl_insecure = true
  }
}

variable "idrac_username" {
  type = string
  sensitive = true
}

variable "idrac_password" {
  type = string
  sensitive = true
}

variable "r930_idrac_endpoint" {
  type = string
  sensitive = true
}
```

### Debug Output

https://gist.github.com/robbycuenot/b1db72eb7a2e2d167498abe2ab140fe7

### Panic Output

None

### Expected Behavior

The data block should have been read and added to the state, as the BIOS attributes did.

### Actual Behavior

After ~10 seconds, an unexpected EOF is received and the iDRAC attributes are not imported to the state

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running on terraform cloud, using a local linux agent with the official TFC container from here: https://hub.docker.com/r/hashicorp/tfc-agent/tags

Other resources work correctly, such as creating user accounts or retrieving BIOS attributes.

It is possible that this is a timeout issue, as the iDRACs tend to have slow response times.

**Comment by gokul-srivathsan** [comment] 2024-06-04 13:05
@robbycuenot We are not able to reproduce in iDrac9. Hence closing this issue. However we will explore ways for giving more clear error message.

**Closed by gokul-srivathsan** 2024-06-04 13:05 UTC
